modules:
  http_2xx:
    http:
      no_follow_redirects: false
      preferred_ip_protocol: ip4
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2
      valid_status_codes: []
    prober: http
    timeout: 10s
  
  http_2xx-general:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: [200,302,301,304] # Defaults to 2xx
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      tls_config:
        insecure_skip_verify: true

  http_post_2xx:
    prober: http
    timeout: 10s
    http:
      method: POST
